//! Source discovery: walks a repository and decides which files are source
//! code worth counting or analysing.

use std::fs;
use std::path::{Path, PathBuf};

use ignore::WalkBuilder;
use serde::{Deserialize, Serialize};

use super::language::Language;
use crate::error::{AnalyzerError, Result};

/// Directory names that are never descended into, regardless of `.gitignore`.
pub const EXCLUDED_DIRS: &[&str] = &[
    ".git",
    "target",
    "build",
    "dist",
    "vendor",
    "node_modules",
    ".svelte-kit",
    "__pycache__",
];

/// Markers that conventionally identify machine-generated files.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "code generated by",
    "automatically generated",
];

/// How many leading lines are inspected for generated-file markers.
const GENERATED_HEADER_LINES: usize = 5;

#[derive(Debug, Clone)]
pub struct DiscoveryOptions {
    pub respect_gitignore: bool,
    /// Files larger than this are skipped (typically data or generated code).
    pub max_file_bytes: u64,
}

impl Default for DiscoveryOptions {
    fn default() -> Self {
        Self {
            respect_gitignore: true,
            max_file_bytes: 2 * 1024 * 1024,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DiscoveredFile {
    /// Repository-relative path with `/` separators.
    pub path: String,
    #[serde(skip)]
    pub abs_path: PathBuf,
    pub language: Language,
    pub bytes: u64,
    /// Non-blank lines.
    pub loc: u32,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SkippedFiles {
    pub generated: u32,
    pub too_large: u32,
    pub not_utf8: u32,
}

#[derive(Debug, Clone, Default)]
pub struct Discovery {
    /// Sorted by path for deterministic downstream processing.
    pub files: Vec<DiscoveredFile>,
    /// Repository-relative paths of every `Cargo.toml`.
    pub cargo_manifests: Vec<String>,
    pub skipped: SkippedFiles,
}

pub fn discover(root: &Path, options: &DiscoveryOptions) -> Result<Discovery> {
    let mut discovery = Discovery::default();

    let walker = WalkBuilder::new(root)
        .hidden(true)
        .git_ignore(options.respect_gitignore)
        .git_exclude(options.respect_gitignore)
        .ignore(options.respect_gitignore)
        .require_git(false)
        .sort_by_file_name(|a, b| a.cmp(b))
        .filter_entry(|entry| {
            let is_dir = entry.file_type().is_some_and(|t| t.is_dir());
            !(is_dir && entry.depth() > 0 && is_excluded_dir(entry.file_name()))
        })
        .build();

    for entry in walker {
        let entry = entry?;
        if !entry.file_type().is_some_and(|t| t.is_file()) {
            continue;
        }
        let abs_path = entry.path();
        let rel_path = relative_path(root, abs_path);

        if entry.file_name() == "Cargo.toml" {
            discovery.cargo_manifests.push(rel_path);
            continue;
        }
        let Some(language) = Language::from_path(abs_path) else {
            continue;
        };
        if is_generated_name(&rel_path) {
            discovery.skipped.generated += 1;
            continue;
        }

        let bytes = entry.metadata()?.len();
        if bytes > options.max_file_bytes {
            discovery.skipped.too_large += 1;
            continue;
        }

        let content = match fs::read_to_string(abs_path) {
            Ok(content) => content,
            Err(err) if err.kind() == std::io::ErrorKind::InvalidData => {
                discovery.skipped.not_utf8 += 1;
                continue;
            }
            Err(err) => return Err(AnalyzerError::io(abs_path, err)),
        };
        if has_generated_header(&content) {
            discovery.skipped.generated += 1;
            continue;
        }

        discovery.files.push(DiscoveredFile {
            path: rel_path,
            abs_path: abs_path.to_path_buf(),
            language,
            bytes,
            loc: count_loc(&content),
        });
    }

    discovery.files.sort_by(|a, b| a.path.cmp(&b.path));
    discovery.cargo_manifests.sort();
    Ok(discovery)
}

fn is_excluded_dir(name: &std::ffi::OsStr) -> bool {
    name.to_str().is_some_and(|n| EXCLUDED_DIRS.contains(&n))
}

fn is_generated_name(path: &str) -> bool {
    let file = path.rsplit('/').next().unwrap_or(path);
    file.ends_with(".pb.rs")
        || file.contains("_generated.")
        || file.contains(".generated.")
        || file.ends_with(".min.js")
}

fn has_generated_header(content: &str) -> bool {
    content.lines().take(GENERATED_HEADER_LINES).any(|line| {
        let line = line.to_ascii_lowercase();
        GENERATED_MARKERS.iter().any(|marker| line.contains(marker))
    })
}

/// Counts non-blank lines. Comment lines are included; distinguishing them
/// reliably requires a parser, which only exists for analysable languages.
pub fn count_loc(content: &str) -> u32 {
    content.lines().filter(|l| !l.trim().is_empty()).count() as u32
}

pub(crate) fn relative_path(root: &Path, path: &Path) -> String {
    let rel = path.strip_prefix(root).unwrap_or(path);
    rel.components()
        .map(|c| c.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(root: &Path, rel: &str, content: &str) {
        let path = root.join(rel);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    fn paths(d: &Discovery) -> Vec<&str> {
        d.files.iter().map(|f| f.path.as_str()).collect()
    }

    #[test]
    fn skips_excluded_directories() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, "src/lib.rs", "fn a() {}\n");
        write(root, "target/debug/build/out.rs", "fn b() {}\n");
        write(root, "node_modules/pkg/index.js", "x\n");
        write(root, "vendor/dep/lib.rs", "fn c() {}\n");
        write(root, "web/dist/app.js", "x\n");
        write(root, "web/src/app.ts", "let x = 1;\n");

        let d = discover(root, &DiscoveryOptions::default()).unwrap();
        assert_eq!(paths(&d), vec!["src/lib.rs", "web/src/app.ts"]);
    }

    #[test]
    fn respects_gitignore_without_a_git_directory() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".gitignore", "ignored/\n");
        write(root, "ignored/x.rs", "fn x() {}\n");
        write(root, "kept.rs", "fn k() {}\n");

        let d = discover(root, &DiscoveryOptions::default()).unwrap();
        assert_eq!(paths(&d), vec!["kept.rs"]);

        let all = discover(
            root,
            &DiscoveryOptions {
                respect_gitignore: false,
                ..Default::default()
            },
        )
        .unwrap();
        assert_eq!(paths(&all), vec!["ignored/x.rs", "kept.rs"]);
    }

    #[test]
    fn skips_generated_and_oversized_files() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, "src/proto.pb.rs", "fn p() {}\n");
        write(root, "src/gen.rs", "// @generated by build.rs\nfn g() {}\n");
        write(root, "src/big.rs", &"fn f() {}\n".repeat(100));
        write(root, "src/ok.rs", "fn ok() {}\n");

        let d = discover(
            root,
            &DiscoveryOptions {
                max_file_bytes: 500,
                ..Default::default()
            },
        )
        .unwrap();
        assert_eq!(paths(&d), vec!["src/ok.rs"]);
        assert_eq!(d.skipped.generated, 2);
        assert_eq!(d.skipped.too_large, 1);
    }

    #[test]
    fn collects_cargo_manifests_and_counts_loc() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, "Cargo.toml", "[workspace]\n");
        write(root, "crates/a/Cargo.toml", "[package]\nname = \"a\"\n");
        write(
            root,
            "crates/a/src/lib.rs",
            "fn a() {}\n\n\n// note\nfn b() {}\n",
        );

        let d = discover(root, &DiscoveryOptions::default()).unwrap();
        assert_eq!(d.cargo_manifests, vec!["Cargo.toml", "crates/a/Cargo.toml"]);
        assert_eq!(d.files[0].loc, 3);
    }
}
